language: python

services:
  - xvfb

jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8

before_install:
  - python3 --version || python --version
  - pip3 install --upgrade pip
  - sudo apt-get install cups
  - sudo apt-get install libcups2-dev

install:
  - pip3 install .

script:
  - python3 setup.py pytest